image:
      name: gcr.io/collabkare-250512/collabkare
      username: _json_key
      password: '$GCLOUD_API_KEYFILE'
clone:           # the 'clone' sectio
  depth: 1       # the depth, in this  case the clone will contain last one commits

pipelines:
  default:
    - step:
        script:
          - echo "Please use a GitFlow branch"
          - exit 1;
  branches:
    developer:
      - step:
          name: build the source code and push into aws-ecr         
          caches:
            - maven
          script:
            - export TARGET_ENV=cndev 
            - echo "developer branch"
            - echo "built Successfully"
          #  - cd ci
          #  - . ci-0-set-properties.sh
          #  - . ci-1-build-project.sh
            
          # SETUP 
          #  - SDK_VERSION=197.0.0
          #  - SDK_FILENAME=google-cloud-sdk-${SDK_VERSION}-linux-x86_64.tar.gz
          #  - curl -o /tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/${SDK_FILENAME}
          #  - tar -xvf /tmp/google-cloud-sdk.tar.gz -C /tmp/
          #  - /tmp/google-cloud-sdk/install.sh -q
          #  - source /tmp/google-cloud-sdk/path.bash.inc
          #  - gcloud -v
          #  - gcloud components install kubectl
          #  - cd ci
          #  - . ci-2-login-into-gcr.sh
          #  - . ci-3-push-into-gcr.sh
            #- cd cd
            #- . cd-update-gke-image.sh
            
    master:
      - step:
          name: build the source code and push into aws-ecr
          caches:
            - maven
          script:
            - export TARGET_ENV=cnprod
            - echo "Master branch"
            - cd ci
            - . ci-0-set-properties.sh
            - . ci-1-build-project.sh
            
          # SETUP 
            - SDK_VERSION=197.0.0
            - SDK_FILENAME=google-cloud-sdk-${SDK_VERSION}-linux-x86_64.tar.gz
            - curl -o /tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/${SDK_FILENAME}
            - tar -xvf /tmp/google-cloud-sdk.tar.gz -C /tmp/
            - /tmp/google-cloud-sdk/install.sh -q
            - source /tmp/google-cloud-sdk/path.bash.inc
            - gcloud -v
            - gcloud components install kubectl
            - cd ci
            - . ci-2-login-into-gcr.sh
            - . ci-3-push-into-gcr.sh
            #- . ci-4-update-gke-image.sh   

options:
  docker: true 
          